# .github/workflows/ci-cd.yml

name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      env:
        INDEX_NAME: ${{ vars.INDEX_NAME }}
        INDEX_SOURCE_TAG: ${{ vars.INDEX_SOURCE_TAG }}
        LANGCHAIN_ENDPOINT: ${{ vars.LANGCHAIN_ENDPOINT }}
        LANGCHAIN_TRACING_V2: ${{ vars.LANGCHAIN_TRACING_V2 }}
        PINECONE_CLOUD: ${{ vars.PINECONE_CLOUD }}
        PINECONE_REGION: ${{ vars.PINECONE_REGION }}
        USER_AGENT: ${{ vars.USER_AGENT }}
      run: |
        python -m pytest

  # deploy:
  #   needs: test
  #   runs-on: ubuntu-latest
  #   if: github.ref == 'refs/heads/main' && github.event_name == 'push'
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Deploy to production
  #     run: |
  #       echo "Add your deployment steps here"
  #       # For example:
  #       # - ssh into your server
  #       # - pull the latest changes
  #       # - restart your application