name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 .

    - name: Format code with black
      run: |
        pip install black
        black --check .

    - name: Run tests
      env:
        INDEX_NAME: ${{ vars.INDEX_NAME }}
        INDEX_SOURCE_TAG: ${{ vars.INDEX_SOURCE_TAG }}
        LANGCHAIN_ENDPOINT: ${{ vars.LANGCHAIN_ENDPOINT }}
        LANGCHAIN_TRACING_V2: ${{ vars.LANGCHAIN_TRACING_V2 }}
        PINECONE_CLOUD: ${{ vars.PINECONE_CLOUD }}
        PINECONE_REGION: ${{ vars.PINECONE_REGION }}
        USER_AGENT: ${{ vars.USER_AGENT }}
        INDEX_HOST: ${{ secrets.INDEX_HOST }}
        AI21_API_KEY: ${{ secrets.AI21_API_KEY }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
        LANGCHAIN_API_KEY: ${{ secrets.LANGCHAIN_API_KEY }}
      run: |
        python -m pytest
